### ISSUE TITLE
Enable Travis CI tests

### ISSUE THREAD

**Issue by amilajack** [extensibleweb/webidl.js#89]
Would be great if travis tests could be enabled for this repo

**Comment by marcoscaceres** [comment]
Agree! You want to help? We currently don't have anyone maintaining this project and could use some help.

**Comment by amilajack** [comment]
I'm not very experienced in parsers and ast's unfortunately. I'm using this project for [a project that i'm working on. It's basically 'caniuse' as an eslint rule](https://github.com/amilajack/eslint-plugin-compat).

Here's a small demo:

![demo of plugin usage](https://raw.githubusercontent.com/amilajack/eslint-plugin-compat/master/img/eslint-plugin-compat-demo.gif)

I want to use WebIDL definitions to check determine which API's are supported in certain browsers, but i'm not sure how to do this at the moment.
